### ISSUE TITLE
Why blog.z.cash is not accessible?

### ISSUE THREAD

**Issue by hasinitg** [zcash/zcash-blog#7]
Hi, 

I have followed a very nice set of blog posts from blog.z.cash on ZK-SNARKs. E.g: this is the topic and link to the first blog post in the series: Explaining SNARKs Part I: Homomorphic Hidings – Zcash Blog. https://blog.z.cash/snark-explain/.

However, when I try to access it, the browser gives a security warning and hence can not access it anymore. Have you moved those posts to somewhere else?

Thank you.

**Comment by ianamunoz** [comment]
Loads normally for myself and a colleague. Where you loading from? what security warning do you get?

**Comment by hasinitg** [comment]
Thank you for the reply. I am accessing from the USA.
Following is the warning I get from firefox (there is no way to add an exception and bypass this)
_Your connection is not secure
The owner of blog.z.cash has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate._

I also get warnings from Safari and Chrome. Following is the warning from chrome:
_NET::ERR_CERT_AUTHORITY_INVALID_

**Comment by ianamunoz** [comment]
You browsing behind a proxy or something? The certificates are valid.

**Comment by hasinitg** [comment]
Thank you for the reply. It seems to be an issue only in my location. I asked a friend to verify and he could access from a different location.

**Comment by daira** [comment]
It's very likely that your connection was being intercepted by a certificate-replacing proxy.
